version: 0.2

phases:
  pre_build:
    commands:
      - sudo yum update -y
      - sudo yum install -y httpd php php-mysql php-dom php-gd mysql git
  build:
    commands:
      - # Add your build commands here
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
     - '**/*'
  discard-paths: no
